themes:
  - name: "vague"
    colors:
      - "#141415"
      - "#1c1c24"
      - "#cdcdcd"
      - "#878787"
      - "#252530"
      - "#606079"
      - "#b4d4cf"
      - "#c48282"
      - "#e8b589"
      - "#e0a363"
      - "#c3c3d5"
      - "#aeaed1"
      - "#bb9dbd"
      - "#333738"
      - "#d8647e"
      - "#f3be7c"
      - "#7e98e8"
      - "#90a0b5"
      - "#6e94b2"
      - "#9bb4bc"
      - "#405065"
      - "#7fa563"
      - "#f3be7c"
